export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";
export const CLEAR_CART="CLEAR_CART";


export const PLACE_ORDER_REQUEST="PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS="PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL="PLACE_ORDER_FAIL";