export const ADD_CATEGORY_REQUEST="ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS="ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL="ADD_CATEGORY_FAIL";

export const DELETE_CATEGORY_REQUEST="DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS="DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL="DELETE_CATEGORY_FAIL";