export const GET_ORDER_REQUEST="GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS="GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL="GET_ORDER_FAIL";

export const GET_ADMIN_ORDER_REQUEST="GET_ADMIN_ORDER_REQUEST";
export const GET_ADMIN_ORDER_SUCCESS="GET_ADMIN_ORDER_SUCCESS";
export const GET_ADMIN_ORDER_FAIL="GET_ADMIN_ORDER_FAIL";

export const PROCESS_ORDER_REQUEST="PROCESS_ORDER_REQUEST";
export const PROCESS_ORDER_SUCCESS="PROCESS_ORDER_SUCCESS";
export const PROCESS_ORDER_FAIL="PROCESS_ORDER_FAIL";